# Generated by Django 2.0.5 on 2018-05-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('adults_only', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TvStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='tvprogram',
            name='tv_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv.TvStation'),
        ),
    ]
